// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu26eq5b7avzX7zeMRmKRevqrl4wLgih8',
    appId: '1:969335092916:web:3fa4e375ee7ed8239b09e1',
    messagingSenderId: '969335092916',
    projectId: 'maizeplant-1ae8a',
    authDomain: 'maizeplant-1ae8a.firebaseapp.com',
    databaseURL: 'https://maizeplant-1ae8a-default-rtdb.firebaseio.com/',
    storageBucket: 'maizeplant-1ae8a.appspot.com',
    measurementId: 'G-QCRJR9JJ11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8IwTsnRZrziadSMLAkR4X5bKwUbuWH1E',
    appId: '1:969335092916:android:529bea70763c68eb9b09e1',
    messagingSenderId: '969335092916',
    projectId: 'maizeplant-1ae8a',
    databaseURL: 'https://maizeplant-1ae8a-default-rtdb.firebaseio.com/',
    storageBucket: 'maizeplant-1ae8a.appspot.com',
  );
}
